name: "Test Publish"

on:
  push:
    branches:
      - main
      
jobs:
  publish:
    name: Test Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.1
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://register.npmjs.org'
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
